//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace EntityFrameworkCodeFirst
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public class DBContext : DbContext
    {
        static DBContext()
    	{ 
    		Database.SetInitializer<DBContext>(null);
    	}
    	
    	public DBContext() : base("name=DBContext")
        {
        }
    	
    	public DBContext(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
    		modelBuilder.Configurations.Add(new Faturat_Mapping());
    		modelBuilder.Configurations.Add(new Klientat_Mapping());
        }
    	
        public DbSet<Faturat> Faturats { get; set; }
        public DbSet<Klientat> Klientats { get; set; }
    }
}
