//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCodeFirst
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using System.ComponentModel.DataAnnotations.Schema;
    internal partial class Faturat_Mapping : EntityTypeConfiguration<Fatura>
    {
        public Faturat_Mapping()
        {					
    		this.HasKey(t => t.ID);		
    		this.ToTable("Faturat");
    		this.Property(t => t.ID).HasColumnName("ID");
    		this.Property(t => t.KlientiID).HasColumnName("KlientiID");
    		this.Property(t => t.Nr).HasColumnName("Nr").IsRequired().HasMaxLength(50);
    		this.Property(t => t.Data).HasColumnName("Data");
    		this.Property(t => t.Shuma).HasColumnName("Shuma");
    		this.HasRequired(t => t.Klienti).WithMany(t => t.Faturat).HasForeignKey(d => d.KlientiID);
    	}
    }
}
