//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCodeFirst
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public class Klienti
    {
        public Klienti()
        {
            this.Faturat = new HashSet<Fatura>();
        }
    
        public int ID { get; set; }
        public string Emri { get; set; }
        public string Mbiemri { get; set; }
        public string Adresa { get; set; }

        public virtual ICollection<Fatura> Faturat { get; set; }
    }
}
