<?xml version="1.0" encoding="utf-8"?><Database Name="DataTest" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Klientat" Member="Klientats">
    <Type Name="Klientat">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Emri" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mbiemri" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Adresa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Klientat_Faturat" Member="Faturats" ThisKey="ID" OtherKey="KlientiID" Type="Faturat" />
    </Type>
  </Table>
  <Table Name="dbo.Faturat" Member="Faturats">
    <Type Name="Faturat">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KlientiID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nr" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Shuma" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Klientat_Faturat" Member="Klientat" ThisKey="KlientiID" OtherKey="ID" Type="Klientat" IsForeignKey="true" />
    </Type>
  </Table>
</Database>